jobs:
  main:
    image: node:12
    requires: [~pr, ~commit]
    steps:
      - echo: echo "hello"
      - committer: |
          curl -H "Authorization: Bearer $SD_TOKEN" "$SD_API_URLevents/$SD_EVENT_ID" | jq '.creator.name'
