jobs:
  main:
    image: node:12
    requires: [~pr, ~commit]
    steps:
      - echo: echo "hello"
      - committer: |
          sleep 5m;
          curl -H "Authorization: Bearer $SD_TOKEN" $SD_API_URL/events/$SD_EVENT_ID | jq '.creator.name'
